In [ ]:
import sys
import os
script_path = os.getcwd()
crime_dir = os.path.abspath(os.path.join(script_path, ".."))
sys.path.insert(0, crime_dir)
from sklearn.metrics import accuracy_score
from Processing.misc import calculate_performance_stats_by_class
from sklearn.metrics import confusion_matrix
import numpy as np

generated_data = [1,1,0,3,3,3]
correct_data = [0,1,1,2,2,3]

confusion = confusion_matrix(correct_data, generated_data)
print(confusion)
overall_accuracy = np.diag(confusion).sum() / confusion.sum()
print(overall_accuracy)
sk_accuracy = accuracy_score(correct_data, generated_data)
print(sk_accuracy)
accuracy_weights = np.array([1, 1, 0, 1])
total_dataset_count = np.sum(confusion, axis=1)
overall_accuracy = np.diag(confusion*np.diag(accuracy_weights)).sum() / np.sum(total_dataset_count*accuracy_weights)
print(total_dataset_count)
mean_dataset_count = np.mean(total_dataset_count)
prop_by_class = mean_dataset_count/ total_dataset_count
accuracy_weights = prop_by_class
print(accuracy_weights)
overall_accuracy = np.diag(confusion*np.diag(accuracy_weights)).sum() / np.sum(total_dataset_count*accuracy_weights)
print(overall_accuracy)

[[0 1 0 0]
 [1 1 0 0]
 [0 0 0 2]
 [0 0 0 1]]
0.3333333333333333
0.3333333333333333
[1 2 2 1]
[1.5  0.75 0.75 1.5 ]
0.375
